UPDATE `Content` SET `ContainerObjectPrintPreview` = 'false' WHERE `ContainerObjectType` = 'XhtmlPicture';

INSERT INTO `ProtectionLayerModules` (`ObjectType`, `ObjectTypeName`, `ObjectTypeLocation`, `ObjectTypeConfiguration`, `ObjectTypePrintPreview`, `ModuleFileName1`, `ModuleFileName2`, `ModuleFileName3`, `ModuleFileName4`, `ModuleFileName5`, `ModuleFileName6`, `ModuleFileName7`, `ModuleFileName8`, `ModuleFileName9`, `ModuleFileName10`, `Enable/Disable`) VALUES ('FileTracker', 'filetracker', 'Modules/Tier3ProtectionLayer/Core/FileTracker', NULL, 'false', 'ClassFileTracker', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable');
INSERT INTO `ProtectionLayerTables` (`ObjectType`, `ObjectTypeName`, `DatabaseTable1`, `DatabaseTable2`, `DatabaseTable3`, `DatabaseTable4`, `DatabaseTable5`, `DatabaseTable6`, `DatabaseTable7`, `DatabaseTable8`, `DatabaseTable9`, `DatabaseTable10`) VALUES ('FileTracker', 'filetracker', 'FileTracker', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

CREATE TABLE `ContentLayerPageTypesDefines` (
  `PageType` varchar(100) NOT NULL,
  `PageTypeID` int(11) NOT NULL,
  `ContainerObjectType` enum('XhtmlContent','XhtmlPicture','XhtmlTable','XhtmlContentForm','XhtmlUnorderedList','XhtmlFlash','XhtmlNews','XhtmlMenu','XhtmlCalendarTable','XhtmlNewsStories','XhtmlForm','XhtmlSimpleViewer','XhtmlFlashJWPlayer') default NULL,
  `ContainerObjectTypeName` enum('content','picture','newspicture','table','contentform','list','menulist','flash','adpicture1','adpanel1','calendar','news','form','simpleviewer','flashjwplayer') NOT NULL,
  `ContainerObjectPrintPreview` enum('true','false') NOT NULL default 'false',
  `ContainerObjectTypeSystemName` varchar(100) default NULL,
  `RepeatStart` enum('true','false') NOT NULL default 'false',
  `RepeatEnd` enum('true','false') NOT NULL default 'false',
  `Empty` enum('true','false') NOT NULL default 'false',
  `StartTag` enum('<div>','<p>') default NULL,
  `EndTag` enum('</div>','</p>') default NULL,
  `StartTagID` text,
  `StartTagStyle` text,
  `StartTagClass` text,
  `HeadingSystemName` varchar(100) default NULL,
  `HeadingStartTag` enum('<h1>','<h2>','<h3>','<h4>','<h5>','<h6>') default NULL,
  `HeadingEndTag` enum('</h1>','</h2>','</h3>','</h4>','</h5>','</h6>') default NULL,
  `HeadingStartTagID` text,
  `HeadingStartTagStyle` text,
  `HeadingStartTagClass` text,
  `ContentSystemName` varchar(100) default NULL,
  `ContentStartTag` enum('<div>','<p>','<blockquote>') default NULL,
  `ContentEndTag` enum('</div>','</p>','</blockquote>') default NULL,
  `ContentStartTagID` text,
  `ContentStartTagStyle` text,
  `ContentStartTagClass` text,
  `ContentPTagID` text,
  `ContentPTagStyle` text,
  `ContentPTagClass` text,
  UNIQUE KEY `PageType` (`PageType`,`PageTypeID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

REPLACE INTO AdministratorFormButton VALUES(230, 2, 'Add SimpleViewer 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'AddGallery1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'AddGallery1', 'en-us', NULL, NULL, 'en-us', NULL, 'AddGallery(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO AdministratorFormButton VALUES(230, 3, 'Remove SimpleViewer 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'RemoveGallery1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'RemoveGallery1', 'en-us', NULL, NULL, 'en-us', NULL, 'RemoveGallery(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

REPLACE INTO AdministratorFormButton VALUES(233, 2, 'Add SimpleViewer 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'AddGallery1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'AddGallery1', 'en-us', NULL, NULL, 'en-us', NULL, 'AddGallery(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO AdministratorFormButton VALUES(233, 3, 'Remove SimpleViewer 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'RemoveGallery1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'RemoveGallery1', 'en-us', NULL, NULL, 'en-us', NULL, 'RemoveGallery(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'LastSimpleViewerPage', '0');

UPDATE `AdministratorList` SET `Li14` = '<a href=''index.php?PageID=239''>SimpleViewer Page</a>' WHERE `AdministratorList`.`PageID` = 11 AND `AdministratorList`.`ObjectID` = 3;

CREATE TABLE `AdPanelLookup` (
  `AdvertisingTableName` varchar(100) NOT NULL,
  `AdPanelName` varchar(100) NOT NULL,
  UNIQUE KEY `AdvertisingTableName` (`AdvertisingTableName`,`AdPanelName`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

REPLACE INTO `AdministratorList` VALUES(10, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''index.php?PageID=11''>Content Management:</a>', 'BodyText', NULL, 2, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Administrator''s Panel:', 'BodyText', NULL, 3, NULL, NULL, NULL, NULL, NULL, 'Enable', 'User Management:', 'BodyText', NULL, 4, NULL, NULL, NULL, NULL, NULL, 'Disable', 'Reports:', 'BodyText', NULL, 5, NULL, NULL, NULL, NULL, NULL, 'Disable', 'Site Building:', 'BodyText', NULL, 6, NULL, NULL, NULL, NULL, NULL, 'Disable', '<a href=''index.php?PageID=15''>Site Configuration:</a>', 'BodyText', NULL, 7, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(10, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Advertising', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Content', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Menu', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Sitemap', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'XML Feeds', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(10, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href="Panel/Managers/StatsManager/StatsManager.php">Stats/Reports Manager</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(10, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Add Users', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Remove Users', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Create Users', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Update Users', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(10, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Site Stats', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(10, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Menus', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Modules', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Themes', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(10, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Site Settings', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Upgrade System', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'System Utilities', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');

REPLACE INTO `AdministratorMainMenu` VALUES(1, 1, '<div>', '</div>', 'main-menu-middle', NULL, NULL, NULL, 'menu', 'main-menu', NULL, '<a href="index.php?PageID=10">Home</a>', NULL, 'MenuItem1', 'menuparent MenuText MenuLi', NULL, 'Enable', '<a href="index.php?PageID=11">Content</a>', NULL, 'MenuItem2', 'menuparent MenuText MenuLi', NULL, 'Enable', '<a href="Panel/Managers/StatsManager/StatsManager.php">Panel</a>', NULL, 'MenuItem3', 'menuparent MenuText MenuLi', NULL, 'Enable', '<a href="index.php?PageID=12">User</a>', NULL, 'MenuItem4', 'menuparent MenuText MenuLi', NULL, 'Disable', '<a href="index.php?PageID=13">Reports</a>', NULL, 'MenuItem5', 'menuparent MenuText MenuLi', NULL, 'Disable', '<a href="index.php?PageID=14">Building</a>', NULL, 'MenuItem6', 'menuparent MenuText MenuLi', NULL, 'Disable', '<a href="index.php?PageID=15">Settings</a>', NULL, 'MenuItem7', 'menuparent MenuText MenuLi', NULL, 'Enable', '<a href="logoff.php">Log Out</a>', NULL, 'MenuItem8', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem9', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem10', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem11', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem12', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem13', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem14', 'menuparent MenuText MenuLi', NULL, 'Enable', NULL, NULL, 'MenuItem15', 'menuparent MenuText MenuLi', NULL, 'Enable', 'Enable', 'Approved');

INSERT INTO `AdministratorContentLayerModulesSettings` (`ObjectType`, `ObjectTypeName`, `Setting`, `SettingAttribute`) VALUES ('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerTableName', 'FlashSimpleViewerLookup');

REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyCreatedPage', '../../index.php?PageID=221');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyCreatedUpdatePage', '../../index.php?PageID=224');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyDeletePage', '../../index.php?PageID=226');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyDeleteSelectPage', '225');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyEnableDisablePage', '../../index.php?PageID=228');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyEnableDisableSelectPage', '227');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyUpdatePage', '../../index.php?PageID=223');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerGalleyUpdateSelectPage', '222');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageCreatedPage', '../../index.php?PageID=231');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageCreatedUpdatePage', '../../index.php?PageID=234');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageDeletePage', '../../index.php?PageID=236');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageDeleteSelectPage', '235');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageEnableDisablePage', '../../index.php?PageID=238');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageEnableDisableSelectPage', '237');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageUpdatePage', '../../index.php?PageID=233');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerPageUpdateSelectPage', '232');
REPLACE INTO `AdministratorContentLayerModulesSettings` VALUES('XhtmlSimpleViewer', 'simpleviewer', 'SimpleViewerTableName', 'FlashSimpleViewerLookup');

UPDATE `AdministratorContentLayerTables` SET `DatabaseTable1` = 'SimpleViewer' WHERE CONVERT(`AdministratorContentLayerTables`.`ObjectType` USING utf8) = 'XhtmlSimpleViewer' AND CONVERT(`AdministratorContentLayerTables`.`ObjectTypeName` USING utf8) = 'simpleviewer' LIMIT 1;
