INSERT INTO `AdministratorPageAttributes` VALUES(27, 0, 'true', 'Create Menu Item', 'favicon.ico', 'rss.php', NULL, NULL, NULL, 'keywords', 'description', NULL, NULL, NULL, 'One Solution CMS, CMS, PHP, PHP 5, Tier, 8 Tier Design', 'One Solution CMS is a new and initiative Content Management System that was created for PHP 5 and MySql. One Solution CMS uses Object Oriented PHP.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorPageAttributes` VALUES(28, 0, 'true', 'Update Menu Item', 'favicon.ico', 'rss.php', NULL, NULL, NULL, 'keywords', 'description', NULL, NULL, NULL, 'KC Photo and Video, photography, video, photos, motorsports, Northeastern NY', 'KC Photo and Video shoots photos and videos from area motorsports and team sports events. Check out the coverage of these great events in the Northeastern NY area.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorPageAttributes` VALUES(29, 0, 'true', 'Update Menu Item', 'favicon.ico', 'rss.php', NULL, NULL, NULL, 'keywords', 'description', NULL, NULL, NULL, 'KC Photo and Video, photography, video, photos, motorsports, Northeastern NY', 'KC Photo and Video shoots photos and videos from area motorsports and team sports events. Check out the coverage of these great events in the Northeastern NY area.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorPageAttributes` VALUES(30, 0, 'true', 'Updated Menu Item', 'favicon.ico', 'rss.php', NULL, NULL, NULL, 'keywords', 'description', NULL, NULL, NULL, 'KC Photo and Video, photography, video, photos, motorsports, Northeastern NY', 'KC Photo and Video shoots photos and videos from area motorsports and team sports events. Check out the coverage of these great events in the Northeastern NY area.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

ALTER TABLE `AdministratorPageAttributes` ORDER BY `PageID`;

UPDATE `AdministratorPageAttributes` SET `MetaNameContent1` = 'One Solution CMS, CMS, PHP, PHP 5, Tier, 8 Tier Design';
UPDATE `AdministratorPageAttributes` SET `MetaNameContent2` = 'One Solution CMS is a new and initiative Content Management System that was created for PHP 5 and MySql. One Solution CMS uses Object Oriented PHP.';

UPDATE `AdministratorPageAttributes` SET `PageTitle` = 'Update Menu Item' WHERE `AdministratorPageAttributes`.`PageID` = 27 AND `AdministratorPageAttributes`.`RevisionID` = 0 LIMIT 1; 
UPDATE `AdministratorPageAttributes` SET `PageTitle` = 'Update Menu Item' WHERE `AdministratorPageAttributes`.`PageID` = 28 AND `AdministratorPageAttributes`.`RevisionID` = 0 LIMIT 1;

INSERT INTO `AdministratorHeaderPanel1` VALUES(27, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'header-sitename', NULL, NULL, '<h1 class=''MainHeading''>One Solution CMS</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(27, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'header-pagename', NULL, NULL, '<h1 class=''SecondaryHeading''>Create Menu Item</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(28, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'header-sitename', NULL, NULL, '<h1 class=''MainHeading''>One Solution CMS</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(28, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'header-pagename', NULL, NULL, '<h1 class=''SecondaryHeading''>Update Menu Item</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(29, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'header-sitename', NULL, NULL, '<h1 class=''MainHeading''>One Solution CMS</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(29, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'header-pagename', NULL, NULL, '<h1 class=''SecondaryHeading''>Update Menu Item</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(30, 1, NULL, NULL, NULL, NULL, NULL, NULL, 'header-sitename', NULL, NULL, '<h1 class=''MainHeading''>One Solution CMS</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorHeaderPanel1` VALUES(30, 2, NULL, NULL, NULL, NULL, NULL, NULL, 'header-pagename', NULL, NULL, '<h1 class=''SecondaryHeading''>Updated Menu Item</h1>', NULL, NULL, NULL, NULL, 'Enable', 'Approved');

ALTER TABLE `AdministratorHeaderPanel1` ORDER BY `PageID`;

INSERT INTO `AdministratorContent` VALUES(27, 0, 'XhtmlContent', 'admincontent', 1, 'true', 0, 'true', 'false', '<div>', NULL, 'main-content-middle', NULL, NULL, 'Create Menu Item', '<h2>', '</h2>', NULL, NULL, 'BodyHeading', 'Please use fill in the form to create a new menu item.', '<p>', '</p>', NULL, NULL, 'BodyText', NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(27, 1, 'XhtmlForm', 'form', 1, 'true', 0, 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(27, 2, 'XhtmlContent', 'admincontent', 3, 'true', 0, 'true', 'false', NULL, '</div>', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(28, 0, 'XhtmlContent', 'admincontent', 1, 'true', 0, 'true', 'false', '<div>', NULL, 'main-content-middle', NULL, NULL, 'Update Menu Item', '<h2>', '</h2>', NULL, NULL, 'BodyHeading', 'Please select the menu item to update.', '<p>', '</p>', NULL, NULL, 'BodyText', NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(28, 1, 'XhtmlForm', 'form', 1, 'true', 0, 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(28, 2, 'XhtmlContent', 'admincontent', 3, 'true', 0, 'true', 'false', NULL, '</div>', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(29, 0, 'XhtmlContent', 'admincontent', 1, 'true', 0, 'true', 'false', '<div>', NULL, 'main-content-middle', NULL, NULL, 'Update Menu Item', '<h2>', '</h2>', NULL, NULL, 'BodyHeading', 'Please use the form to update a menu item.', '<p>', '</p>', NULL, NULL, 'BodyText', NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(29, 1, 'XhtmlForm', 'form', 1, 'true', 0, 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(29, 2, 'XhtmlContent', 'admincontent', 3, 'true', 0, 'true', 'false', NULL, '</div>', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(30, 0, 'XhtmlContent', 'admincontent', 1, 'true', 0, 'true', 'false', '<div>', NULL, 'main-content-middle', NULL, NULL, 'Updated Main Menu', '<h2>', '</h2>', NULL, NULL, 'BodyHeading', 'The menu item has been updated.', '<p>', '</p>', NULL, NULL, 'BodyText', NULL, NULL, 'BodyText', 'Enable', 'Approved');
INSERT INTO `AdministratorContent` VALUES(30, 1, 'XhtmlContent', 'admincontent', 2, 'true', 0, 'true', 'false', NULL, '</div>', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

ALTER TABLE `AdministratorContent` ORDER BY `ObjectID`;
ALTER TABLE `AdministratorContent` ORDER BY `PageID`;

INSERT INTO `AdministratorContentLayerVersion` VALUES(23, 0, 'true', 'FormPage', NULL, NULL, 1, 'Guest', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(24, 0, 'true', 'FormPage', NULL, NULL, 1, 'Guest', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(25, 0, 'true', 'FormPage', NULL, NULL, 1, 'Guest', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(26, 0, 'true', 'FormPage', NULL, NULL, 1, 'Guest', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(27, 0, 'true', 'FormPage', NULL, NULL, 1, 'User', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(28, 0, 'true', 'FormPage', NULL, NULL, 1, 'Administrator', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(29, 0, 'true', 'FormPage', NULL, NULL, 1, 'Administrator', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);
INSERT INTO `AdministratorContentLayerVersion` VALUES(30, 0, 'true', 'ContentPage', NULL, NULL, 1, 'Administrator', 'TravisNapoleanSmith', 'TravisNapoleanSmith', 'TravisNapoleanSmith', '2010-06-07 20:18:16', '2010-06-07 20:18:22', NULL, NULL);

ALTER TABLE `AdministratorContentLayerVersion` ORDER BY `PageID`;

INSERT INTO `AdministratorForm` VALUES(27, 1, 'AdministratorFormTableListing', 'System/Menu/AddMenuItem.php', NULL, NULL, 'multipart/form-data', 'post', NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorForm` VALUES(28, 1, 'AdministratorFormTableListing', 'System/Menu/SelectMenuItem.php', NULL, NULL, 'multipart/form-data', 'post', NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorForm` VALUES(29, 1, 'AdministratorFormTableListing', 'System/Menu/UpdateMenuItem.php', NULL, NULL, 'multipart/form-data', 'post', NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

ALTER TABLE `AdministratorForm` ORDER BY `PageID`;

INSERT INTO `AdministratorFormButton` VALUES(27, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Login', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '27', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormButton` VALUES(28, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Register', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '28', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormButton` VALUES(29, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'PasswordCreation', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '29', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

ALTER TABLE `AdministratorFormButton` ORDER BY `PageID`;

INSERT INTO `AdministratorFormTableListing` VALUES(27, 1, 'FieldSet', 'AdministratorFormFieldSet', 1, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormTableListing` VALUES(27, 2, 'Button', 'AdministratorFormButton', 1, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormTableListing` VALUES(28, 1, 'FieldSet', 'AdministratorFormFieldSet', 1, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormTableListing` VALUES(28, 2, 'Button', 'AdministratorFormButton', 1, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormTableListing` VALUES(29, 1, 'FieldSet', 'AdministratorFormFieldSet', 1, NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormTableListing` VALUES(29, 2, 'Button', 'AdministratorFormButton', 1, NULL, NULL, NULL, 'Enable', 'Approved');

ALTER TABLE `AdministratorFormTableListing` ORDER BY `PageID`;

INSERT INTO `AdministratorFormLabel` VALUES(27, 1, 'Menu Item Name', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(27, 2, 'Menu Item Title', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(27, 3, 'Enabled', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(27, 4, 'Status', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(28, 1, 'Menu Item', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(29, 1, 'Menu Item Name', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(29, 2, 'Menu Item Title', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(29, 3, 'Enabled', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormLabel` VALUES(29, 4, 'Status', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

ALTER TABLE `AdministratorFormLabel` ORDER BY `PageID`;

INSERT INTO `AdministratorFormInput` VALUES(27, 1, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuName', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormInput` VALUES(27, 2, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuTitle', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormInput` VALUES(29, 1, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuName', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormInput` VALUES(29, 2, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuTitle', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

ALTER TABLE `AdministratorFormInput` ORDER BY `PageID`;

INSERT INTO `AdministratorFormLegend` (`PageID`, `ObjectID`, `FormLegendText`, `FormLegendTextDynamic`, `FormLegendTextTableName`, `FormLegendTextField`, `FormLegendTextPageID`, `FormLegendTextObjectID`, `FormLegendTextRevisionID`, `FormLegendAccessKey`, `FormLegendClass`, `FormLegendDir`, `FormLegendID`, `FormLegendLang`, `FormLegendStyle`, `FormLegendTitle`, `FormLegendXMLLang`, `Enable/Disable`, `Status`) VALUES ('27', '1', 'Create Menu Item', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyHeading', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved'), ('28', '1', 'Update Menu Item', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyHeading', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved'), ('29', '1', 'Update Menu Item', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyHeading', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

ALTER TABLE `AdministratorFormLegend` ORDER BY `PageID`;

INSERT INTO `AdministratorFormOption` VALUES(27, 1000000, 'Enable', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(27, 1000001, 'Disable', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(27, 1000002, 'Approved', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(27, 1000003, 'Not-Approved', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(27, 1000004, 'Spam', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(27, 1000005, 'Pending', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(29, 1000000, 'Enable', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(29, 1000001, 'Disable', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(29, 1000002, 'Approved', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(29, 1000003, 'Not-Approved', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(29, 1000004, 'Spam', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormOption` VALUES(29, 1000005, 'Pending', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

ALTER TABLE `AdministratorFormOption` ORDER BY `PageID`;

INSERT INTO `AdministratorFormSelect` VALUES(27, 1000000, 1000002, NULL, 'Option', 'AdministratorFormOption', 1000000, NULL, NULL, 'EnableDisable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000001, 1000002, NULL, 'Option', 'AdministratorFormOption', 1000001, NULL, NULL, 'EnableDisable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000002, 1000002, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'width: 550px;', NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000003, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000002, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000004, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000003, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000005, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000004, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000006, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000005, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(27, 1000007, 1000007, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'width: 550px;', NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000000, 1000002, NULL, 'Option', 'AdministratorFormOption', 1000000, NULL, NULL, 'EnableDisable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000001, 1000002, NULL, 'Option', 'AdministratorFormOption', 1000001, NULL, NULL, 'EnableDisable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000002, 1000002, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'width: 550px;', NULL, NULL, NULL, 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000003, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000002, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000004, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000003, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000005, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000004, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000006, 1000007, NULL, 'Option', 'AdministratorFormOption', 1000005, NULL, NULL, 'Status', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', 'width: 550px;', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormSelect` VALUES(29, 1000007, 1000007, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'width: 550px;', NULL, NULL, NULL, 'Enable', 'Approved');

ALTER TABLE `AdministratorFormSelect` ORDER BY `PageID`;

INSERT INTO `AdministratorFormFieldSet` VALUES(27, 1, NULL, 'Legend', 'AdministratorFormLegend', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 2, NULL, 'Label', 'AdministratorFormLabel', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 3, NULL, 'Input', 'AdministratorFormInput', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 4, NULL, 'Label', 'AdministratorFormLabel', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 5, NULL, 'Input', 'AdministratorFormInput', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 6, NULL, 'Label', 'AdministratorFormLabel', 3, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 7, NULL, 'Select', 'AdministratorFormSelect', 1000000, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 8, NULL, 'Label', 'AdministratorFormLabel', 4, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(27, 9, NULL, 'Select', 'AdministratorFormSelect', 1000003, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(28, 1, NULL, 'Legend', 'AdministratorFormLegend', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(28, 2, NULL, 'Label', 'AdministratorFormLabel', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(28, 3, NULL, 'Select', 'AdministratorFormSelect', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 1, NULL, 'Legend', 'AdministratorFormLegend', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 2, NULL, 'Label', 'AdministratorFormLabel', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 3, NULL, 'Input', 'AdministratorFormInput', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 4, NULL, 'Label', 'AdministratorFormLabel', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 5, NULL, 'Input', 'AdministratorFormInput', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 6, NULL, 'Label', 'AdministratorFormLabel', 3, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 7, NULL, 'Select', 'AdministratorFormSelect', 1000000, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 8, NULL, 'Label', 'AdministratorFormLabel', 4, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
INSERT INTO `AdministratorFormFieldSet` VALUES(29, 9, NULL, 'Select', 'AdministratorFormSelect', 1000003, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

ALTER TABLE `AdministratorFormFieldSet` ORDER BY `PageID`;

REPLACE INTO `AdministratorForm` VALUES(20, 1, 'AdministratorFormTableListing', 'System/Menu/SelectMenu.php', NULL, NULL, NULL, 'post', NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorForm` VALUES(21, 1, 'AdministratorFormTableListing', 'System/Menu/UpdateMenu.php', NULL, NULL, NULL, 'post', NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorForm` VALUES(2, 1, 'AdministratorFormTableListing', 'System/Register/Register.php', NULL, NULL, NULL, 'post', NULL, NULL, 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
UPDATE `AdministratorContentLayerModulesSettings` SET `SettingAttribute` = '../../index.php?PageID=2' WHERE CONVERT(`AdministratorContentLayerModulesSettings`.`ObjectType` USING utf8) = 'ContentLayer' AND CONVERT(`AdministratorContentLayerModulesSettings`.`ObjectTypeName` USING utf8) = 'ContentLayer' AND CONVERT(`AdministratorContentLayerModulesSettings`.`Setting` USING utf8) = 'Register' LIMIT 1;
UPDATE `AdministratorContentLayerModulesSettings` SET `SettingAttribute` = '../../index.php?PageID=3' WHERE CONVERT(`AdministratorContentLayerModulesSettings`.`ObjectType` USING utf8) = 'ContentLayer' AND CONVERT(`AdministratorContentLayerModulesSettings`.`ObjectTypeName` USING utf8) = 'ContentLayer' AND CONVERT(`AdministratorContentLayerModulesSettings`.`Setting` USING utf8) = 'RegisterRedirect' LIMIT 1;

REPLACE INTO `AdministratorContentLayerTheme` VALUES('AdminTheme', '../Tier8-PresentationLayer/AdminTheme/Settings.css', '../Tier8-PresentationLayer/AdminTheme/TextSettings.css', '../Tier8-PresentationLayer/AdminTheme/Menus.css', '../Tier8-PresentationLayer/AdminTheme/MenuSettings.css', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/dhtmlxgrid.css', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/skins/dhtmlxgrid_dhx_skyblue.css', '../Libraries/Tier7BehavioralLayer/DHTMLXVault/codebase/dhtmlxvault.css', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '../Tier8-PresentationLayer/AdminTheme/SettingsIE6.css', '../Tier8-PresentationLayer/AdminTheme/MenuSettingsIE6.css', NULL, NULL, NULL, '../Tier8-PresentationLayer/AdminTheme/MenuSettingsIE7.css', '../Tier8-PresentationLayer/AdminTheme/SettingsIE7.css', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/dhtmlxcommon.js', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/dhtmlxgrid.js', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/dhtmlxgridcell.js', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/ext/dhtmlxgrid_form.js', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/ext/dhtmlxgrid_mcol.js', '../Libraries/Tier7BehavioralLayer/jQuery/jquery-1.9.1.min.js', '../Libraries/Tier7BehavioralLayer/DHTMLXSuiteStandard/codebase/ext/dhtmlxgrid_drag.js', '../Libraries/Tier7BehavioralLayer/DHTMLXVault/codebase/dhtmlxvault.js', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable');

REPLACE INTO `AdministratorFormButton` VALUES(150, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'AddVideoPage', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '150', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(150, 2, 'Add Content 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'AddVideo1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'AddContent1', 'en-us', NULL, NULL, 'en-us', NULL, 'AddContent(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(150, 3, 'Remove Content 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'RemoveContent1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'RemoveContent1', 'en-us', NULL, NULL, 'en-us', NULL, 'RemoveContent(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(152, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'UpdateVideoPage', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '152', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(153, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'UpdateVideoPage', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '153', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(153, 2, 'Add Content 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'AddContent1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'AddContent1', 'en-us', NULL, NULL, 'en-us', NULL, 'AddContent(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(153, 3, 'Remove Content 1', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'RemoveContent1', NULL, NULL, NULL, NULL, NULL, NULL, 'button', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm ShortFormButton', 'ltr', 'RemoveContent1', 'en-us', NULL, NULL, 'en-us', NULL, 'RemoveContent(1);', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(155, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'DeleteVideoPage', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '155', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(157, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'EnableDisableVideoPage', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '157', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

UPDATE `MainMenuItemLookup` SET `ParentIDName` = NULL;

CREATE TABLE `SiteStatsDailyCurrent` (
  `PageID` int(11) NOT NULL,
  `Count` int(11) NOT NULL default '0',
  UNIQUE KEY `PageID` (`PageID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

UPDATE `ContentLayerTables` SET `DatabaseTable2` = 'SiteStatsDailyCurrent' WHERE CONVERT(`ContentLayerTables`.`ObjectType` USING utf8) = 'XhtmlSiteStats' AND CONVERT(`ContentLayerTables`.`ObjectTypeName` USING utf8) = 'sitestats' LIMIT 1;

UPDATE `AdministratorList` SET `Li3` = '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLDailySiteStatsListing.php?Format=XML''>Daily Site Stats as XML Format</a>', `Li4` = '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLDailySiteStatsListing.php?Format=CSV''>Daily Site Stats as CSV Format</a>' WHERE `AdministratorList`.`PageID` = 15 AND `AdministratorList`.`ObjectID` = 5 LIMIT 1;
