INSERT INTO `AdministratorContentLayerModulesSettings` (`ObjectType`, `ObjectTypeName`, `Setting`, `SettingAttribute`) VALUES ('XhtmlHeader', 'header', 'MetaTags', NULL);
INSERT INTO `AdministratorContentLayerModulesSettings` (`ObjectType`, `ObjectTypeName`, `Setting`, `SettingAttribute`) VALUES ('XhtmlHeader', 'header', 'Description', NULL);

INSERT INTO `AdministratorContentLayerModulesSettings` (`ObjectType`, `ObjectTypeName`, `Setting`, `SettingAttribute`) VALUES ('XhtmlMainMenu', 'mainmenu', 'AddMenuItem', '27'), ('XhtmlMainMenu', 'mainmenu', 'CreatedUpdateMenuItem', '../../index.php?PageID=30'), ('XhtmlMainMenu', 'mainmenu', 'UpdateMenuItem', '../../index.php?PageID=29'), ('XhtmlMainMenu', 'mainmenu', 'UpdateMenuItemSelect', '28');

UPDATE `AdministratorContent` SET `Heading` = 'Added / Updated Menu Item', `Content` = 'The menu item has been added or updated.' WHERE `AdministratorContent`.`PageID` = 30 AND `AdministratorContent`.`ObjectID` = 0 AND `AdministratorContent`.`RevisionID` = 0 LIMIT 1;

UPDATE `AdministratorHeaderPanel1` SET `Div1` = "<h1 class='SecondaryHeading'>Added / Updated Menu Item</h1>" WHERE `AdministratorHeaderPanel1`.`PageID` = 30 AND `AdministratorHeaderPanel1`.`ObjectID` = 2 LIMIT 1;

UPDATE `AdministratorPageAttributes` SET `PageTitle` = 'Added / Updated Menu Item' WHERE `AdministratorPageAttributes`.`PageID` = 30 AND `AdministratorPageAttributes`.`RevisionID` = 0 LIMIT 1;

INSERT INTO `AdministratorContentLayerModulesSettings` (`ObjectType`, `ObjectTypeName`, `Setting`, `SettingAttribute`) VALUES ('XhtmlMainMenu', 'mainmenu', 'LastMenuItem', '0');

DELETE FROM `AdministratorFormValidation` WHERE `AdministratorFormValidation`.`PageID` = 110 AND CONVERT(`AdministratorFormValidation`.`FormFieldName` USING utf8) = 'AddPhotosPage' LIMIT 1;

REPLACE INTO `AdministratorFormButton` VALUES(27, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'AddMenuItem', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '27', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(28, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'SelectMenuItem', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '28', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');
REPLACE INTO `AdministratorFormButton` VALUES(29, 1, 'Submit', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'UpdateMenuItem', NULL, NULL, NULL, NULL, NULL, NULL, 'submit', '29', NULL, NULL, NULL, NULL, NULL, NULL, 'BodyTextButton ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Approved');

UPDATE `AdministratorPageAttributes` SET `PageTitle` = 'Create Menu Item' WHERE `AdministratorPageAttributes`.`PageID` = 27 AND `AdministratorPageAttributes`.`RevisionID` = 0 LIMIT 1;

INSERT INTO `AdministratorContentLayerModulesSettings` (`ObjectType`, `ObjectTypeName`, `Setting`, `SettingAttribute`) VALUES ('XhtmlMainMenu', 'mainmenu', 'StartPageID', '1000000000');

REPLACE INTO `AdministratorFormLabel` VALUES(27, 1, 'Menu Item Name', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(27, 2, 'Menu Item Title', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(27, 3, 'Menu Item Link', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(27, 4, 'Enabled', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(27, 5, 'Status', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorFormLabel` VALUES(29, 1, 'Menu Item Name', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(29, 2, 'Menu Item Title', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(29, 3, 'Menu Item Link', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(29, 4, 'Enabled', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormLabel` VALUES(29, 5, 'Status', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorFormInput` VALUES(27, 1, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuName', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormInput` VALUES(27, 2, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuTitle', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormInput` VALUES(27, 3, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuLink', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorFormInput` VALUES(29, 1, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuName', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormInput` VALUES(29, 2, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuTitle', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormInput` VALUES(29, 3, NULL, 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MenuLink', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'text', 'NULL', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 1, NULL, 'Legend', 'AdministratorFormLegend', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 2, NULL, 'Label', 'AdministratorFormLabel', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 3, NULL, 'Input', 'AdministratorFormInput', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 4, NULL, 'Label', 'AdministratorFormLabel', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 5, NULL, 'Input', 'AdministratorFormInput', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 6, NULL, 'Label', 'AdministratorFormLabel', 3, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 7, NULL, 'Input', 'AdministratorFormInput', 3, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 8, NULL, 'Label', 'AdministratorFormLabel', 4, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 9, NULL, 'Select', 'AdministratorFormSelect', 1000000, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 10, NULL, 'Label', 'AdministratorFormLabel', 5, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(27, 11, NULL, 'Select', 'AdministratorFormSelect', 1000003, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 1, NULL, 'Legend', 'AdministratorFormLegend', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 2, NULL, 'Label', 'AdministratorFormLabel', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 3, NULL, 'Input', 'AdministratorFormInput', 1, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 4, NULL, 'Label', 'AdministratorFormLabel', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 5, NULL, 'Input', 'AdministratorFormInput', 2, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 6, NULL, 'Label', 'AdministratorFormLabel', 3, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 7, NULL, 'Input', 'AdministratorFormInput', 3, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 8, NULL, 'Label', 'AdministratorFormLabel', 4, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 9, NULL, 'Select', 'AdministratorFormSelect', 1000000, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 10, NULL, 'Label', 'AdministratorFormLabel', 5, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');
REPLACE INTO `AdministratorFormFieldSet` VALUES(29, 11, NULL, 'Select', 'AdministratorFormSelect', 1000003, NULL, NULL, NULL, 'false', NULL, NULL, NULL, NULL, NULL, 'BodyText ShortForm', 'ltr', NULL, 'en-us', NULL, NULL, 'en-us', 'Enable', 'Approved');

REPLACE INTO `AdministratorFormValidation` VALUES(27, 'AddMenuItem', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(27, 'EnableDisable', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(27, 'MenuLink', 'AlphaNum', NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(27, 'MenuName', 'AlphaNum', NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(27, 'MenuTitle', 'AlphaNum', NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(27, 'Status', NULL, NULL, NULL, NULL, NULL);

REPLACE INTO `AdministratorFormValidation` VALUES(29, 'UpdateMenuItem', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(29, 'EnableDisable', NULL, NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(29, 'MenuLink', 'AlphaNum', NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(29, 'MenuName', 'AlphaNum', NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(29, 'MenuTitle', 'AlphaNum', NULL, NULL, NULL, NULL);
REPLACE INTO `AdministratorFormValidation` VALUES(29, 'Status', NULL, NULL, NULL, NULL, NULL);

ALTER TABLE `AdministratorFormValidation` ORDER BY `PageID`;

CREATE TABLE `SiteStatsIPAddress` (
  `PageID` int(11) NOT NULL,
  `IPAddress` varchar(20) NOT NULL,
  `Count` int(11) NOT NULL,
  UNIQUE KEY `PageID` (`PageID`,`IPAddress`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `SiteStatsIPAddressDailyCurrent` (
  `PageID` int(11) NOT NULL,
  `IPAddress` varchar(20) NOT NULL,
  `Count` int(11) NOT NULL,
  UNIQUE KEY `PageID` (`PageID`,`IPAddress`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `SiteStatsTimestampLogCurrent` (
  `Timestamp` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `PageID` int(11) NOT NULL,
  `IPAddress` varchar(20) default NULL,
  `RefferPageID` int(11) default NULL,
  `UserAgentString` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

REPLACE INTO `ContentLayerTables` VALUES('XhtmlSiteStats', 'sitestats', 'SiteStats', 'SiteStatsDailyCurrent', 'SiteStatsIPAddress', 'SiteStatsIPAddressDailyCurrent', 'SiteStatsTimestampLogCurrent', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

ALTER TABLE `SiteStatsTimestampLogCurrent` CHANGE `RefferPageID` `RefferPageID` TEXT NULL;

ALTER TABLE `SiteStatsTimestampLogCurrent` CHANGE `RefferPageID` `ReferPageID` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

REPLACE INTO `AdministratorList` VALUES(15, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Site Settings:', 'BodyText', NULL, 2, NULL, NULL, NULL, NULL, NULL, 'Disable', 'Upgrade System:', 'BodyText', NULL, 3, NULL, NULL, NULL, NULL, NULL, 'Enable', 'System Utilities:', 'BodyText', NULL, 4, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Site Stats:', 'BodyText', NULL, 5, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Ad Stats:', 'BodyText', NULL, 6, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Tables Pages:', 'BodyText', NULL, 7, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Videos Pages:', 'BodyText', NULL, 8, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Security Tools:', 'BodyText', NULL, 9, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System Message', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Maintenance Mode', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Server Settings', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''index.php?PageID=23''>Upload System Update</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''SystemUpdater/SystemUpdater.php''>System Updater</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''System/EmptyCaptchaImageDirectory/EmptyCaptchaImageDirectory.php''>Empty Captcha Image Directory</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''System/SessionDataCleanupRemover/SessionDataCleanupRemover.php''>Session Data Cleanup Remover</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''System/PHPInfo/PHPInfo.php''>PHP Configuration Information</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''System/SystemUpdateFileRemover/SystemUpdateFileRemover.php''>System Update File Remover Tool</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''System/SystemUpdateUpgradeFolderRemover/SystemUpdateUpgradeFolderRemover.php''>System Update Upgrade Folder Remover Tool</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''System/DatabaseBackup/DatabaseBackup.php''>Database Backup Utility</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLSiteStatsListing.php?Format=XML''>Site Stats as XML Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLSiteStatsListing.php?Format=CSV''>Site Stats as CSV Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLDailySiteStatsListing.php?Format=XML''>Daily Site Stats as XML Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLIPAddressSiteStatsListing.php?Format=CSV''>Daily Site Stats as CSV Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLIPAddressSiteStatsListing.php?Format=XML''>IP Address Site Stats as XML Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLDailyIPAddressSiteStatsListing.php?Format=CSV''>IP Address Site Stats as CSV Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLDailyIPAddressSiteStatsListing.php?Format=XML''>Daily IP Address Site Stats as XML Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLDailyIPAddressSiteStatsListing.php?Format=CSV''>Daily IP Address Site Stats as CSV Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLTimestampLogListing.php?Format=XML''>Timestamp Site Stats as XML Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Core/XhtmlSiteStats/XMLTimestampLogListing.php?Format=CSV''>Timestamp Site Stats as CSV Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''../Modules/Tier6ContentLayer/Extended/XhtmlAd/XMLAdStatsListing.php?Format=XML''>Ad Stats as XML Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''../Modules/Tier6ContentLayer/Extended/XhtmlAd/XMLAdStatsListing.php?Format=CSV''>Ad Stats as CSV Format</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''PageTypes/TablePage/EmptyUploadDirectory.php''>Empty Table Upload Directory</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''PageTypes/TablePage/EmptyTempFilesDirectory.php''>Empty Table Temp Files Directory</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''PageTypes/VideosPage/EmptyTempFilesDirectory.php''>Empty Videos Page Temp Files Directory</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');
REPLACE INTO `AdministratorList` VALUES(15, 9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<a href=''System/SystemFileIntegrityScanner/UpdateSystemFileIntegrityDatabaseTable.php''>Update System File Integrity Database Table</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', '<a href=''System/SystemFileIntegrityScanner/SystemFileIntegrityScanner.php''>System File Integrity Scanner</a>', 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', NULL, 'BodyText', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enable', 'Enable', 'Approved');

DELETE FROM `AdministratorFormValidation` WHERE `AdministratorFormValidation`.`PageID` = 200 AND CONVERT(`AdministratorFormValidation`.`FormFieldName` USING utf8) = 'TableContent' LIMIT 1;
DELETE FROM `AdministratorFormValidation` WHERE `AdministratorFormValidation`.`PageID` = 203 AND CONVERT(`AdministratorFormValidation`.`FormFieldName` USING utf8) = 'TableContent' LIMIT 1;

