//v.3.6 build 130417

/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
You allowed to use this component or parts of it under GPL terms
To use it on other terms or get Professional edition of the component please contact us at sales@dhtmlx.com
*/
function dhtmlXPopup(s){var d=this;this.conf=s||{};s=null;this.mode=this.conf.mode||"bottom";this.p=document.createElement("DIV");this.p.style.display="none";this.p.innerHTML="<div class='dhx_popup_area"+(_isIE?" dhx_popup_area_ie":"")+"'><table cellspacing='0' cellpadding='0' border='0' class='dhx_popup_table'><tbody></tbody></table></div><div class='dhx_popup_arrow dhx_popup_arrow_"+this.mode+"'></div>";document.body.appendChild(this.p);this.skinParams={dhx_terrace:{t0:19,t1:9,t2:19,t3:9},dhx_skyblue:{t0:12,
t1:9,t2:12,t3:9},dhx_web:{t0:12,t1:9,t2:12,t3:9}};this.p.onclick=function(a){a=a||event;a.cancelBubble=!0;if(d._nodeObj!=null)return d.callEvent("onContentClick",[]),!0;for(var b=a.target||a.srcElement,c=null;b!=d.p;){if(typeof b._idd!="undefined"&&!b._isSeparator)c=b._idd;b=b.parentNode}b=null;c&&(d.callEvent("onClick",[c]),d!=null&&d.hide())};this.separator="DHXSEP"+(new Date).getTime();this.tpl=[];this.setTemplate=function(a){this.tpl=a.split(",")};this.uid=function(){this.idd?this.idd++:this.idd=
(new Date).getTime();return this.idd};this.show=function(a){var b=null;if(arguments.length==1){if(a){if(!this._idExists(a))return}else a=this.conf.id[0];this.conf.toolbar&&(b=this.conf.toolbar.getItemDim(a));this.conf.form&&(b=this.conf.form.getItemDim(a))}else if(arguments.length==4)this._clearClick=!0,b={left:arguments[0],top:arguments[1],width:arguments[2],height:arguments[3]},a=null;if(b)this.p.style.visibility="hidden",this.p.style.display="",this._setPos(b),this.p.style.visibility="visible",
this._lastId=a,this.callEvent("onShow",[a])};this._setPos=function(a,b){var c=a.left,d=a.top,e=a.width,f=a.height;this._posData={left:c,top:d,width:e,height:f};var h=Math.max((_isIE?document.documentElement:document.getElementsByTagName("html")[0]).scrollLeft,document.body.scrollLeft),k=h+(_isIE?Math.max(document.documentElement.clientWidth||0,document.documentElement.offsetWidth||0,document.body.clientWidth||0):window.innerWidth),m=Math.max((_isIE?document.documentElement:document.getElementsByTagName("html")[0]).scrollTop,
document.body.scrollTop),p=m+(_isIE?Math.max(document.documentElement.clientHeight||0,document.documentElement.offsetHeight||0,document.body.clientHeight||0):window.innerHeight),g=b||this.mode;typeof b=="undefined"&&(b=!1);if(g=="top"||g=="bottom"){if(g=="top"&&d-this.p.offsetHeight<m&&!b){this._setPos(a,"bottom");return}if(!b&&g=="bottom"&&d+f+this.p.offsetHeight>p){this._setPos(a,"top");return}var q=this.skinParams[this.skin].t2,j=this.skinParams[this.skin].t3,s=Math.round(this.p.offsetWidth/2),
t=Math.round(this.p.lastChild.offsetWidth/2);if(c<h)var r=Math.min(c+e,h),e=c+e-r,c=r;c+e>k&&(e=k-c);var i=Math.round(c+e/2),n=i-s,x=i-q-t,y=i+t+q-this.p.offsetWidth;n<h-j?n=Math.min(h-j,x):n+this.p.offsetWidth>k+j&&(n=Math.max(y,k+j-this.p.offsetWidth));this.p.style.left=n+"px";this.p.style.top=(g=="top"?d-this.p.offsetHeight:d+f)+"px";i=i-n-t;this.p.lastChild.className="dhx_popup_arrow dhx_popup_arrow_"+g;this.p.lastChild.style.top=(g=="top"?this.p.offsetHeight-this.p.lastChild.offsetHeight:0)+
"px";this.p.lastChild.style.left=i+"px"}if(g=="left"||g=="right"){if(g=="left"&&c-this.p.offsetWidth<h&&!b){this._setPos(a,"right");return}if(!b&&g=="right"&&c+e+this.p.offsetWidth>k){this._setPos(a,"left");return}var q=this.skinParams[this.skin].t0,j=this.skinParams[this.skin].t1,z=Math.round(this.p.offsetHeight/2),u=Math.round(this.p.lastChild.offsetHeight/2);if(d<m)var w=Math.min(d+f,m),f=d+f-w,d=w;d+f>p&&(f=p-d);var i=Math.round(d+f/2),o=i-z,A=i-q-u,B=i+u+q-this.p.offsetHeight;o<m-j?o=Math.min(m-
j,A):o+this.p.offsetHeight>p+j&&(o=Math.max(B,p+j-this.p.offsetHeight));this.p.style.left=(g=="left"?c-this.p.offsetWidth:c+e)+"px";this.p.style.top=o+"px";i=i-o-u;this.p.lastChild.className="dhx_popup_arrow dhx_popup_arrow_"+g;this.p.lastChild.style.left=(g=="left"?this.p.offsetWidth-this.p.lastChild.offsetWidth:0)+"px";this.p.lastChild.style.top=i+"px"}if(this._IEDisp&&this._nodeId!=null){var v=document.getElementById(this._nodeId);v.style.visibility="hidden";window.setTimeout(function(){v.style.visibility=
"visible";v=null},100)}};this._repaint=function(){this.isVisible()&&this._setPos(this._posData)};this.clear=function(){if(this._nodeObj){if(_isIE&&typeof dhtmlXLayoutObject!="undefined"&&this._nodeObj instanceof dhtmlXLayoutObject)this.p.onmousedown=null;this._nodeObj.unload?this._nodeObj.unload():this._nodeObj.destruct&&this._nodeObj.destruct();this._nodeObj=this._nodeId=null}this._IEHoverInited&&this._IEHoverClear();for(var a=this.p.firstChild.firstChild.firstChild;a.childNodes.length>0;)a.removeChild(a.lastChild);
a=null;this.itemData={}};this.hide=function(){if(this.p.style.display!="none"){this.p.style.display="none";var a=this._lastId;this._lastId=null;this.callEvent("onHide",[a])}};this.isVisible=function(){return this.p.style.display==""};this.itemData={};this.getItemData=function(a){return!a?this.itemData:this.itemData[a]?this.itemData[a]:{}};this.setSkin=function(a){this.skin=a;this.p.className="dhx_popup_"+this.skin;this._nodeObj!=null&&typeof this._nodeObj.setSkin=="function"&&this._nodeObj.setSkin(this.skin);
this._repaint()};this.skinDetect=function(){var a=document.createElement("DIV");a.className="dhx_popup_skin_detect";document.body.firstChild?document.body.insertBefore(a,document.body.firstChild):document.body.appendChild(a);var b=a.offsetWidth;a.parentNode.removeChild(a);a=null;return{10:"dhx_skyblue",20:"dhx_web",30:"dhx_terrace"}[b]||null};this.attachList=function(a,b){this.setTemplate(a);this.clear();for(var c=this.p.firstChild.firstChild.firstChild,d=0;d<b.length;d++){var e=document.createElement("TR");
e._idd=b[d].id||this.uid();c.appendChild(e);this.itemData[e._idd]=b[d];if(b[d]==this.separator){e.className="dhx_popup_sep";e._isSeparator=!0;var f=document.createElement("TD");f.className="dhx_popup_sep";f.colSpan=this.tpl.length;f.innerHTML="<div class='dhx_popup_sep'>&nbsp;</div>";e.appendChild(f);f=null}else{for(var h=0;h<this.tpl.length;h++){var k="dhx_popup_td";if(this._IEFirstLast&&(this.tpl.length==1||h==0||h==this.tpl.length-1))k+=this.tpl.length==1?" dhx_popup_td_single":h==0?" dhx_popup_td_first":
" dhx_popup_td_last";f=document.createElement("TD");f.className=k;f.innerHTML=b[d][this.tpl[h]]||"&nbsp;";e.appendChild(f);f=null}if(this._IEHover)e._IEHover=!0,this._IEHoverInited||this._IEHoverInit()}e=null}c=null;this._repaint()};this.attachObject=function(a){return this._attachNode("object",{obj:a})};this.attachHTML=function(a){return this._attachNode("html",{html:a})};this.attachForm=function(a){return this._attachNode("form",{struct:a})};this.attachCalendar=function(){return this._attachNode("calendar",
{})};this.attachGrid=function(a,b){return this._attachNode("grid",{width:a||400,height:b||200})};this.attachTree=function(a,b,c){return this._attachNode("tree",{width:a||400,height:b||200,rootId:c||0})};this.attachLayout=function(a,b,c){return this._attachNode("layout",{width:a||400,height:b||200,pattern:c||"3L"})};this.attachAccordion=function(a,b){return this._attachNode("accordion",{width:a||400,height:b||200})};this.attachTabbar=function(a,b,c){return this._attachNode("tabbar",{width:a||400,height:b||
200,mode:c||"top"})};this._attachNode=function(a,b){this.clear();this._nodeId="cn_"+(new Date).getTime();var c=this.p.firstChild.firstChild.firstChild,l=document.createElement("TR");l.className="dhxnode";c.appendChild(l);var e=document.createElement("TD");e.className="dhx_popup_td";e.innerHTML="<div id='"+this._nodeId+"' style='position:relative;'></div>";if(b.width)e.firstChild.style.width=b.width+"px";if(b.height)e.firstChild.style.height=b.height+"px";l.appendChild(e);e=l=c=null;if(a=="object")this._nodeObj=
typeof b.obj=="string"?document.getElementById(b.obj):b.obj,b.obj=null,document.getElementById(this._nodeId).appendChild(this._nodeObj),this._nodeObj.style.display="",this._nodeObj.style.visibility="visible";if(a=="html")document.getElementById(this._nodeId).innerHTML=b.html,this._nodeObj={text:b.html};if(a=="form")this._nodeObj=new dhtmlXForm(this._nodeId,b.struct),this._nodeObj.setSkin(this.skin);if(a=="calendar")this._nodeObj=new dhtmlXCalendarObject(this._nodeId),this._nodeObj.setSkin(this.skin),
this._nodeObj.show();if(a=="grid")this._nodeObj=new dhtmlXGridObject(this._nodeId),this._nodeObj.setSkin(this.skin);if(a=="tree")this._nodeObj=new dhtmlXTreeObject(this._nodeId,"100%","100%",b.rootId);if(a=="layout"&&(this._nodeObj=new dhtmlXLayoutObject(this._nodeId,b.pattern,this.skin),_isIE))this.p.onmousedown=function(){d._clearClick=!0};if(a=="accordion")this._nodeObj=new dhtmlXAccordion(this._nodeId,this.skin);if(a=="tabbar")this._nodeObj=new dhtmlXTabBar(this._nodeId,b.mode),this._nodeObj.setSkin(this.skin);
this._repaint();return this._nodeObj};this.unload=function(){window.addEventListener?(window.removeEventListener("click",this._doOnClick,!1),window.removeEventListener("unload",this._doOnUnload,!1)):(document.body.detachEvent("onclick",this._doOnClick,!1),document.body.detachEvent("onunload",this._doOnUnload,!1));this.clear();this._doOnKeyUp=this._doOnUnload=this._doOnClick=null;if(this.conf.toolbarEvent!=null&&this.conf.toolbar!=null)this.conf.toolbar.detachEvent!=null?this.conf.toolbar.detachEvent(this.conf.toolbarEvent):
this.conf.toolbar.getItemDim=null;this.detachAllEvents();this._clearClick=this._lastId=this._posData=this.skinParams=this.skinParent=this.tpl=this.idd=this.uid=this.itemData=this.separator=this.skin=this.mode=this.show=this.hide=this.isVisible=this.setTemplate=this._repaint=this._setPos=this.getItemData=this.clear=this._idExists=this._doOnToolbarClick=this.setSkin=this.skinDetect=this.attachList=this.attachAccordion=this.attachCalendar=this.attachForm=this.attachGrid=this.attachLayout=this.attachTabbar=
this.attachTree=this.attachHTML=this.attachObject=this._attachNode=this.attachEvent=this.detachEvent=this.callEvent=this.checkEvent=this.detachAllEvents=this.eventCatcher=null;this.p.onclick=null;this.p.parentNode.removeChild(this.p);this.p=null;d=this.unload=this._IEDisp=this._IEHover=this._IEHoverTM=this._IEHoverInit=this._IEHoverClear=this._IEHoverRender=this._IEHoverInited=this.conf=this.conf.toolbar=this.conf.toolbarEvent=this.conf.form=this.conf.id=null};dhtmlxEventable(this);this._doOnClick=
function(a){a=a||event;if(d._clearClick)d._clearClick=!1;else{if(d.conf.form!=null){var b,c=a.target||a.srcElement;if((c.tagName||"").toLowerCase()=="option")c=c.parentNode;if(c.className!=null&&c.className.search("dhxform")>=0){if(c.parentNode!=null&&c.parentNode.parentNode!=null&&c.parentNode.parentNode._idd!=null)b=c.parentNode.parentNode._idd,c.parentNode.parentNode._type=="ra"&&(b=[c.parentNode.parentNode._group,c.parentNode.parentNode._value])}else{for(var l=!0,e=!1;l&&!e;)e=(c.className||"").toLowerCase()==
"dhxform_btn"||(c.className||"").search(/dhxeditor_inside/gi)>=0,c=c.parentNode,l=c!=null;if(e)return}c=null;if(b!=null&&d._idExists(b))return}d.hide()}};this._doOnKeyUp=function(a){a=a||event;a.keyCode==27&&d.hide()};this._doOnUnload=function(){d.unload()};window.addEventListener?(window.addEventListener("click",this._doOnClick,!1),window.addEventListener("keyup",this._doOnKeyUp,!1),window.addEventListener("unload",this._doOnUnload,!1)):(document.body.attachEvent("onclick",this._doOnClick,!1),document.body.attachEvent("onkeyup",
this._doOnKeyUp,!1),document.body.attachEvent("onunload",this._doOnUnload,!1));this._idExists=function(a){for(var b=!1,c=0;c<this.conf.id.length;c++)b=this.conf.id[c]instanceof Array?b||this.conf.id[c][0]==a[0]&&this.conf.id[c][1]==a[1]:b||this.conf.id[c]==a;return b};this._IEDisp=_isIE&&navigator.userAgent.search("MSIE 6.0")>=0;if(this._IEHover=_isIE&&navigator.userAgent.search("MSIE 6.0")>=0)this._IEHoverInit=function(){this.p.onmouseover=function(){for(var a=event.srcElement;a!=this&&a._IEHover!=
!0;)a=a.parentNode;a._IEHover&&(d._IEHoverTM&&window.clearTimeout(d._IEHoverTM),d._lastIEHover!=a&&(d._IEHoverRender(a),a=null))};this.p.onmouseout=function(){d._IEHoverTM&&window.clearTimeout(d._IEHoverTM);d._IEHoverTM=window.setTimeout(function(){d._IEHoverRender(null)},1)};this._IEHoverRender=function(a){if(this._lastIEHover!=null&&this._lastIEHover.className.search(/tr_hover/gi)>=0)this._lastIEHover.className=this._lastIEHover.className.replace(/\s{0,}tr_hover/gi,""),this._lastIEHover=null;if(a!=
null&&a.className.search(/tr_hover/gi)<0)a.className+=" tr_hover",d._lastIEHover=a};this._IEHoverInited=!0},this._IEHoverClear=function(){this.p.onmouseover=null;this.p.onmouseout=null;this._IEHoverInited=!1};this._IEFirstLast=_isIE&&navigator.userAgent.search(/MSIE [6,7,8]\.0/i)>=0;if(typeof dhtmlXToolbarObject!="undefined"&&this.conf.toolbar!=null&&this.conf.toolbar instanceof dhtmlXToolbarObject&&this.conf.id!=null){if(!(this.conf.id instanceof Array))this.conf.id=[this.conf.id];this.skinParent=
this.conf.toolbar.skin;this._doOnToolbarClick=function(a){for(var b=0;b<d.conf.id.length;b++)if(a==d.conf.id[b]&&a!=d._lastId)d.show(a),d._clearClick=!0};if(typeof dhtmlXToolbarObject.prototype.getItemDim=="undefined")dhtmlXToolbarObject.prototype.getItemDim=function(a){var b=this.objPull[this.idPrefix+a],c={left:getAbsoluteLeft(b.obj),top:getAbsoluteTop(b.obj),width:b.obj.offsetWidth+(b.arw?b.arw.offsetWidth:0),height:b.obj.offsetHeight},b=null;return c};this.conf.toolbarEvent=this.conf.toolbar.attachEvent("onClick",
d._doOnToolbarClick)}if(typeof dhtmlXForm!="undefined"&&this.conf.form!=null&&this.conf.form instanceof dhtmlXForm&&this.conf.id!=null){if(!(this.conf.id instanceof Array))this.conf.id=[this.conf.id];if(!this.conf.mode)this.mode="right";this.skinParent=this.conf.form.skin;if(typeof dhtmlXForm.prototype.getItemDim=="undefined"){dhtmlXForm.prototype.getItemDim=function(a){return this.doWithItem(a,"_getDim")};for(var r in{input:1,password:1,select:1,multiselect:1,checkbox:1,radio:1,button:1,combo:1,
btn2state:1,calendar:1,colorpicker:1,editor:1})if(dhtmlXForm.prototype.items[r]!=null)dhtmlXForm.prototype.items[r]._getDim=function(a){var b=a;({ta:!0,pw:!0,se:!0,calendar:!0,colorpicker:1,editor:!0})[a._type]&&(b=a.childNodes[a._ll?1:0].childNodes[0]);({ch:!0,ra:!0,btn2state:!0})[a._type]&&(b=a.childNodes[a._ll?1:0].childNodes[1]);if({bt:!0}[a._type])b=a.firstChild;if({combo:!0}[a._type])b=a._combo.DOMParent.firstChild;var c={left:getAbsoluteLeft(b),top:getAbsoluteTop(b),width:b.offsetWidth,height:b.offsetHeight},
b=null;return c}}}this.setSkin(this.conf.skin||(typeof dhtmlx!="undefined"?dhtmlx.skin:null)||this.skinParent||this.skinDetect()||"dhx_skyblue");return this};

//v.3.6 build 130417

/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
You allowed to use this component or parts of it under GPL terms
To use it on other terms or get Professional edition of the component please contact us at sales@dhtmlx.com
*/